# Generated by Django 6.0.4 on 2026-04-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="safe_during_breastfeeding",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="medicine",
            name="safe_during_pregnancy",
            field=models.BooleanField(default=False),
        ),
    ]
