# Generated by Django 6.0.4 on 2026-04-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_location_alter_medicineinstance_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='safe_for_diabetics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='safe_for_hypertensive',
            field=models.BooleanField(default=False),
        ),
    ]
