# Generated by Django 5.1.2 on 2026-04-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_family_location_family_medicineinstance_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='form',
            field=models.CharField(choices=[('tablet', 'قرص'), ('capsule', 'كبسولة'), ('syrup', 'شراب'), ('drops', 'قطرة'), ('cream', 'كريم'), ('injection', 'حقنة'), ('inhaler', 'بخاخ'), ('suppository', 'تحميلة'), ('patch', 'لصقة'), ('other', 'أخرى')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='condition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='familymembership',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicineinstance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
