# Generated by Django 5.1.2 on 2026-04-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_medicine_form_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineinstance',
            name='min_threshold',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medicineinstance',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
