# Generated by Django 5.1.2 on 2026-04-28 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('form', models.CharField(choices=[('tablet', 'قرص'), ('capsule', 'كبسولة'), ('syrup', 'شراب'), ('drops', 'قطرة'), ('cream', 'كريم'), ('injection', 'حقنة'), ('inhaler', 'بخاخ'), ('suppository', 'تحميلة'), ('patch', 'لصقة'), ('other', 'أخرى')], default='tablet', max_length=20)),
                ('shelf_life_months', models.PositiveIntegerField()),
                ('shelf_life_after_opening_months', models.PositiveIntegerField()),
                ('safe_during_pregnancy', models.BooleanField(default=False)),
                ('safe_during_breastfeeding', models.BooleanField(default=False)),
                ('safe_for_diabetics', models.BooleanField(default=False)),
                ('safe_for_hypertensive', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('conditions', models.ManyToManyField(blank=True, to='api.condition')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
