# Generated by Django 5.1.2 on 2026-04-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
