# Generated by Django 5.1.2 on 2026-05-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_moderator_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='schedule_type',
            field=models.CharField(choices=[('fixed_times', 'أوقات محددة'), ('interval', 'كل فترة'), ('weekly', 'أيام محددة')], max_length=20),
        ),
    ]
