# Generated by Django 5.1.2 on 2026-05-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_reminder_end_date_alter_reminder_schedule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinstance',
            name='min_threshold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
